### ISSUE TITLE
USBvalve PCB with through hole solder points

### ISSUE THREAD

**Issue by Manofhunt** [cecio/USBvalve#24]
I am wanting to build a battery powered version for USB checks on the go. I found a battery component that should work but ideally it would go under the custom USBvalve PCB. Would it be possible to get the original CAD for modification or have a Gerber fileset with through hole configuration instead of surface mount?

**Comment by cecio** [comment]
Hey, thanks for you interest in the project.

Unfortunately I don't own the original CAD file, so I can not share it.
I see an issue anyway: if you are going to add headers to the Pico and then solder to the PCB, probably the header of the LCD are not long enough to be soldered (due to the extra space added by Pico the headers), so this modification requires a complete re-design of the PCB itself and the whole form factor.

But I'm wondering: 
- if you add headers to Pico, do you really need the PCB? With a small piece of a PCB Matrix board you can probably obtain the same result and be free to arrange your own design
- keeping the current PCB, I think you should be able to reach the power PINs on the opposite side without much trouble

Thanks :-)
